# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "kanjikata"
license = "MIT"
licenselink = "https://github.com/liodopolus/kanjikata/LICENSE.md"
description = "kanjikata is my private theme."
homepage = "https://www.kanjikata.de/"
tags = []
features = []
min_version = "0.20.7"

[author]
  name = "Jeffrey Scherling"
  homepage = "www.kanjikata.de"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""

